
name = "nnpolitics" # 您的 Worker 名字
main = "worker.js"             # 您的本地 JS 文件名
compatibility_date = "2024-03-08"

# 绑定代码中需要的 D1 数据库
[[d1_databases]]
binding = "DB"                 # 必须和代码中的 env.DB 一致
database_name = "politics-review" 
database_id = "96c209b0-9ff6-4efd-afe7-31ea1d30b3db"



中标太 交付时间
DEPP



1  风味的注释情况、数据库再增加
2  寡糖拼接项目
3  PWAS分析回顾
4  



这次的输入文件要换成input下面的这个文件lab_db_with_qc.tsv，这个表格并不是所有数据都拿来进行训练，主要是拿表格中最后一列含QC。如果是QC合格的，然后作为模型的训练和测试，优化下脚本






整理对云平台的需求，做三年规划，说明计划云平台能实现的目标以及解决的问题：
1 实现特定专业领域的信息手机和AI分析
2 实现自动化进行客户描述自动调取工具进行分析得到图和结果
3 云平台部分小工具能够手机公众号的调取
4 云平台具有特大客户数据计算潜力
5 云平台能够支持客户分析出图格式多样化
6 云平台工具规范化，实现特定接口可以整合获取






